"""Emit a Python behavior file that runs the compiled workflow."""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from ..models import CompiledStep, PlanCompilation, ReplanCheckpoint
from ._tokens import _value_to_python_expr, _contains_token, _literal_python


_REF_HELPER = '''\
def _ref(state, step_id, *path):
    """Resolve state.step_results[step_id] then traverse *path."""
    val = state.step_results.get(step_id, state.initial_parameters.get(step_id))
    for segment in path:
        if val is None:
            return None
        if isinstance(val, list) and str(segment).isdigit():
            idx = int(segment)
            val = val[idx] if idx < len(val) else None
        elif isinstance(val, dict):
            val = val.get(segment)
        elif hasattr(val, segment):
            val = getattr(val, segment)
        else:
            return None
    return val
'''


def emit_behavior(compilation: PlanCompilation, agent_id: str, output_path: str | Path) -> None:
    """Write the Python behavior file for the compiled workflow.

    Args:
        compilation: Compiled planning data.
        agent_id: Identifier for the generated agent (used for class name).
        output_path: Where to write the ``<agent>_behavior.py`` file.
    """
    class_name = _to_class_name(agent_id)
    checkpoint_set = {cp.after_step_id for cp in compilation.replan_checkpoints}

    lines: list[str] = []

    # Header
    lines.append(f"# AUTO-GENERATED by agent_workflow_compiler.")
    lines.append(f"# Source run: {compilation.source_run_id}")
    lines.append(f"# Source agent: {compilation.source_agent_id}")
    lines.append(f"# Edit _on_step_end() to activate replan checkpoints.")
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("from agent_framework.agents.agent_behavior import AgentBehavior, AgentHookDecision")
    lines.append("from agent_framework.agents.workflow import (")
    lines.append("    ProgrammaticWorkflow,")

    # Only import step types that are actually used
    used_kinds = {s.kind for s in compilation.final_steps}
    if "call_subagent" in used_kinds:
        lines.append("    WorkflowCallSubagentStep,")
    if "call_tool" in used_kinds:
        lines.append("    WorkflowCallToolStep,")
    if "invoke_skill" in used_kinds:
        lines.append("    WorkflowInvokeSkillStep,")
    if "call_subagents" in used_kinds:
        lines.append("    WorkflowCallSubagentsStep,")
    lines.append("    WorkflowReturnStep,")
    lines.append("    WorkflowContinue,")
    lines.append("    WorkflowGoto,")
    lines.append("    WorkflowReplace,")
    lines.append(")")
    lines.append("")

    # _ref helper
    lines.append("")
    lines.extend(_REF_HELPER.splitlines())
    lines.append("")

    # _build_workflow()
    lines.append("")
    lines.append("def _build_workflow() -> ProgrammaticWorkflow:")
    lines.append("    return ProgrammaticWorkflow(")
    lines.append(f"        entry_step={repr(compilation.final_steps[0].step_id)},")
    lines.append("        on_step_end=_on_step_end,")
    lines.append("        steps={")

    for i, step in enumerate(compilation.final_steps):
        is_last = i == len(compilation.final_steps) - 1
        lines.extend(_emit_step(step, indent=12, override_next="_wf_final" if is_last else None))

    # Terminal return step
    last_id = compilation.final_steps[-1].step_id if compilation.final_steps else "_wf_final"
    lines.append(f"            '_wf_final': WorkflowReturnStep(")
    lines.append(f"                step_id='_wf_final',")
    lines.append(f"                value=lambda s: s.step_results.get({repr(last_id)}),")
    lines.append(f"            ),")
    lines.append("        },")
    lines.append("    )")
    lines.append("")

    # _on_step_end()
    lines.append("")
    lines.append("def _on_step_end(step_id: str, result: Any, state: Any, workflow: Any):")
    if compilation.replan_checkpoints:
        lines.append("    # Replan checkpoints from source log.")
        lines.append("    # Each checkpoint is where the source planning agent issued a revised plan.")
        lines.append("    # By default these are pass-through (WorkflowContinue).")
        lines.append("    # Replace WorkflowContinue() with WorkflowGoto/WorkflowReplace to activate re-routing.")
        for cp in compilation.replan_checkpoints:
            lines.append(f"    if step_id == {repr(cp.after_step_id)}:")
            lines.append(f"        # Revision {cp.plan_revision}: {cp.trigger_message!r}")
            lines.append(f"        # Added: {cp.added_step_ids}")
            lines.append(f"        return WorkflowContinue()")
    else:
        lines.append("    # No replans occurred in the source run.")
        pass
    lines.append("    return WorkflowContinue()")
    lines.append("")

    # Behavior class
    lines.append("")
    lines.append(f"class {class_name}Behavior(AgentBehavior):")
    lines.append("    def attach(self, agent) -> None:")
    lines.append("        pass")
    lines.append("")
    lines.append("    def before_run(self, agent, host, *, run, caller_id):")
    lines.append("        workflow = _build_workflow()")
    lines.append("        result = agent.execute_programmatic_workflow(")
    lines.append("            host=host, run=run, caller_id=caller_id,")
    lines.append("            workflow=workflow, initial_parameters=run.parameter_values,")
    lines.append("        )")
    lines.append("        return AgentHookDecision(final_result=result)")
    lines.append("")
    lines.append("")
    lines.append(f"def build_behavior() -> AgentBehavior:")
    lines.append(f"    return {class_name}Behavior()")
    lines.append("")

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _emit_step(step: CompiledStep, indent: int, override_next: str | None = None) -> list[str]:
    """Return source lines for one workflow step entry."""
    pad = " " * indent
    lines: list[str] = []
    lines.append(f"{pad}{repr(step.step_id)}: {_step_class(step.kind)}(")
    lines.append(f"{pad}    step_id={repr(step.step_id)},")

    if step.kind == "call_tool":
        lines.append(f"{pad}    tool_name={repr(step.tool_name)},")
        lines.extend(_emit_arguments(step.parameters, pad + "    ", label="arguments"))
    elif step.kind == "call_subagent":
        lines.append(f"{pad}    subagent_id={repr(step.subagent_id)},")
        lines.extend(_emit_arguments(step.parameters, pad + "    ", label="parameters"))
    elif step.kind == "invoke_skill":
        lines.append(f"{pad}    skill_name={repr(step.skill_name)},")
        lines.extend(_emit_arguments(step.parameters, pad + "    ", label="parameters"))

    effective_next = override_next if override_next is not None else step.next_step
    if effective_next is not None:
        lines.append(f"{pad}    next_step={repr(effective_next)},")

    lines.append(f"{pad}),")
    return lines


def _emit_arguments(params: dict[str, Any], pad: str, label: str) -> list[str]:
    """Emit the arguments/parameters dict, wrapping in lambda if tokens present."""
    if not params:
        return []

    if _contains_token(params):
        # Any token in any key → wrap whole dict in a resolver lambda
        lines: list[str] = [f"{pad}{label}={{"]
        for k, v in params.items():
            expr = _value_to_python_expr(v)
            lines.append(f"{pad}    {repr(k)}: {expr},")
        lines.append(f"{pad}}},")
        return lines
    else:
        # Pure literal dict
        pairs = ", ".join(f"{repr(k)}: {_literal_python(v)}" for k, v in params.items())
        return [f"{pad}{label}={{{pairs}}},"]


def _step_class(kind: str) -> str:
    mapping = {
        "call_tool": "WorkflowCallToolStep",
        "call_subagent": "WorkflowCallSubagentStep",
        "invoke_skill": "WorkflowInvokeSkillStep",
        "call_subagents": "WorkflowCallSubagentsStep",
    }
    return mapping.get(kind, "WorkflowCallToolStep")


def _to_class_name(agent_id: str) -> str:
    """Convert snake_case agent_id to PascalCase for class name."""
    return "".join(part.capitalize() for part in agent_id.replace("-", "_").split("_"))
